/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.alkalineResponsiveMenu = {
    attach: function attach(context) {
      $(".navbar nav > ul.menu", context).once("alkalineResponsiveMenu").each(function (index, menu) {
        return new Alkaline.ResponsiveMenu(menu);
      });
    }
  };
})(jQuery, Drupal);