/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.alkalineResponsiveMenu = {
    attach: function attach() {
      $(".navbar nav > ul.menu").once("alkalineResponsiveMenu").each(function (index, menu) {
        var $menu = $(menu).data({
          "responsive-menu": "drilldown large-dropdown",
          backButton: "\n                <li class=\"js-drilldown-back\">\n                  <a tabindex=\"0\">\n                    <span>Back</span>\n                  </a>\n                </li>\n              ",
          autoHeight: true,
          animateHeight: true
        }).addClass("vertical large-horizontal");

        $menu.find("ul.sub-menu").addClass("vertical");

        $menu.responsiveMenu = new Foundation.ResponsiveMenu($menu, {});
      });
    }
  };
})(jQuery, Drupal);